CREATE TABLE [dbo].[Calendar] (
    [DateKey]     INT          NOT NULL,
    [Date]        DATE         NOT NULL,
    [Year]        SMALLINT     NOT NULL,
    [Month]       TINYINT      NOT NULL,
    [Day]         TINYINT      NOT NULL,
    [Week]        TINYINT      NOT NULL,
    [Quarter]     TINYINT      NOT NULL,
    [WeekDay]     TINYINT      NOT NULL,
    [DayOfYear]   SMALLINT     NOT NULL,
    [IsWeekend]   BIT          NOT NULL,
    [IsHoliday]   BIT          NOT NULL,
    [HolidayName] VARCHAR (30) NULL,
    [MonthName]   VARCHAR (20) NOT NULL,
    [WeekDayName] VARCHAR (20) NOT NULL,
    [A1_res_id]   INT          NULL,
    [A2_res_id]   INT          NULL,
    [A3_res_id]   INT          NULL,
    [A4_res_id]   INT          NULL,
    [A5_res_id]   INT          NULL,
    [B1_res_id]   INT          NULL,
    [B2_res_id]   INT          NULL,
    [B3_res_id]   INT          NULL,
    [B4_res_id]   INT          NULL,
    [B5_res_id]   INT          NULL,
    [C1_res_id]   INT          NULL,
    [C2_res_id]   INT          NULL,
    [C3_res_id]   INT          NULL,
    [C4_res_id]   INT          NULL,
    [C5_res_id]   INT          NULL,
    CONSTRAINT [PK_Calendar] PRIMARY KEY CLUSTERED ([DateKey] ASC),
    CONSTRAINT [FK_Calendar_reservations] FOREIGN KEY ([A1_res_id]) REFERENCES [dbo].[reservations] ([Id]),
    CONSTRAINT [FK_Calendar_reservations1] FOREIGN KEY ([A1_res_id]) REFERENCES [dbo].[reservations] ([Id]),
    CONSTRAINT [FK_Calendar_reservations10] FOREIGN KEY ([B5_res_id]) REFERENCES [dbo].[reservations] ([Id]),
    CONSTRAINT [FK_Calendar_reservations11] FOREIGN KEY ([C1_res_id]) REFERENCES [dbo].[reservations] ([Id]),
    CONSTRAINT [FK_Calendar_reservations12] FOREIGN KEY ([C2_res_id]) REFERENCES [dbo].[reservations] ([Id]),
    CONSTRAINT [FK_Calendar_reservations13] FOREIGN KEY ([C3_res_id]) REFERENCES [dbo].[reservations] ([Id]),
    CONSTRAINT [FK_Calendar_reservations14] FOREIGN KEY ([C4_res_id]) REFERENCES [dbo].[reservations] ([Id]),
    CONSTRAINT [FK_Calendar_reservations15] FOREIGN KEY ([C5_res_id]) REFERENCES [dbo].[reservations] ([Id]),
    CONSTRAINT [FK_Calendar_reservations2] FOREIGN KEY ([A2_res_id]) REFERENCES [dbo].[reservations] ([Id]),
    CONSTRAINT [FK_Calendar_reservations3] FOREIGN KEY ([A3_res_id]) REFERENCES [dbo].[reservations] ([Id]),
    CONSTRAINT [FK_Calendar_reservations4] FOREIGN KEY ([A4_res_id]) REFERENCES [dbo].[reservations] ([Id]),
    CONSTRAINT [FK_Calendar_reservations5] FOREIGN KEY ([A5_res_id]) REFERENCES [dbo].[reservations] ([Id]),
    CONSTRAINT [FK_Calendar_reservations6] FOREIGN KEY ([B1_res_id]) REFERENCES [dbo].[reservations] ([Id]),
    CONSTRAINT [FK_Calendar_reservations7] FOREIGN KEY ([B2_res_id]) REFERENCES [dbo].[reservations] ([Id]),
    CONSTRAINT [FK_Calendar_reservations8] FOREIGN KEY ([B3_res_id]) REFERENCES [dbo].[reservations] ([Id]),
    CONSTRAINT [FK_Calendar_reservations9] FOREIGN KEY ([B4_res_id]) REFERENCES [dbo].[reservations] ([Id]),
    CONSTRAINT [UC_Calendar_Date] UNIQUE NONCLUSTERED ([Date] ASC)
);

